### ISSUE TITLE
Fix dict lookup error for networks and volumes

### ISSUE THREAD

**Issue by uchenic** [uchenic/compose-to-nomad#3]
https://github.com/uchenic/compose-to-nomad/blob/master/composenomadconvertor/produce_tasks.py#L50
and 
https://github.com/uchenic/compose-to-nomad/blob/master/composenomadconvertor/produce_tasks.py#L128

**Comment by maxadamo** [comment]
I tried either your pip package, and the code from the master branch of this repository. 
I am having an issue because my Compose does not have a `networks` key defined. I know nearly nothing about Compose, but I understand that the networks parameter is not mandatory (I have 3 Compose files, and none of them is using this key). 

I paste one of my 3 files (the smaller that I have):

```yaml
version: '3'
services:

  influxdb:
    image: influxdb:2.0
    env_file: ./influxdb/.env
    restart: always
    volumes:
      - influxdbv2:/var/lib/influxdb2
      - influxdbv2_cfg:/etc/influxdb2
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:7.4.3
    env_file: ./grafana/.env
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana

  apache:
    image: timemap_proxy 
    env_file: ./timemap_proxy/shibboleth.env
    links:
      - grafana
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./timemap_proxy/apache2/certs:/etc/apache2/certs:ro
      - ./timemap_proxy/shibboleth/sp-cert.pem:/etc/shibboleth/sp-cert.pem:ro
      - ./timemap_proxy/shibboleth/sp-key.pem:/etc/shibboleth/sp-key.pem:ro
        
volumes:
  influxdbv2:
  influxdbv2_cfg:
  grafana:
```
